export const CAMPAIGN_LOAD = 'CAMPAIGN_LOAD';
export const CAMPAIGN_LOAD_SUCCESS = 'CAMPAIGN_LOAD_SUCCESS';
export const CAMPAIGN_LOAD_FAIL = 'CAMPAIGN_LOAD_FAIL';

export const SET_CURRENT_CAMPAIGN = 'SET_CURRENT_CAMPAIGN';